@AngularAspDotNetCore.Server_HostAddress = http://localhost:5165

### ToDoList

### get all lists
GET {{AngularAspDotNetCore.Server_HostAddress}}/api/todolist/
Accept: application/json

### get list by id
GET {{AngularAspDotNetCore.Server_HostAddress}}/api/todolist/{{$guid}}
Accept: application/json

### create new list
POST {{AngularAspDotNetCore.Server_HostAddress}}/api/todolist/
Content-Type: application/json

{
  "id": "{{$guid}}",
  "name": "Sample List",
  "items": [
    {
      "id": "{{$guid}}",
      "title": "Sample ToDo Item",
      "isDone": false
    }
  ]
}

### update existing list
PUT {{AngularAspDotNetCore.Server_HostAddress}}/api/todolist/
Content-Type: applicatino/json

{
  "id": "{{$guid}}",
  "name": "Updated ToDo List Name",
  "items": [
    {
      "id": "{{$guid}}",
      "title": "Updated ToDo Item",
      "isComplete": true
    }
  ]
}

### delete list by id
DELETE {{AngularAspDotNetCore.Server_HostAddress}}/api/todolist/{{$guid}}
Accept: application/json

###

### ToDoItems

### get all items
GET {{AngularAspDotNetCore.Server_HostAddress}}/api/todoitem
Accept: application/json

### create new item
POST {{AngularAspDotNetCore.Server_HostAddress}}/api/todoitem
Content-Type: application/json

{
  "id": "{{$guid}}",
  "title": "Sample ToDo Item",
  "isDone": false,
  "toDoListId": "{{$guid}}"
}

### update existing item
PUT {{AngularAspDotNetCore.Server_HostAddress}}/api/todoitem
Content-Type: application/json

{
  "id": "{{$guid}}",
  "title": "Updated Item",
  "isDone": true,
  "toDoListId": "{{$guid}}"
}

### delte item by id
DELETE {{AngularAspDotNetCore.Server_HostAddress}}/api/todoitem/{{$guid}}
Accept: applicatin/json

###